### ISSUE TITLE
The importFactory flag's value ignored

### ISSUE THREAD

**Issue by PTihomir** [rebem/layers-loader#6]
Hi
Just as the documentation says, the importFactory flag changes what is returned by using `#`. But for some reason, when requesting a component in the consumer component (in a file defined as consumer in the rebem-layers-loader configuration) the returned value is always wrapped in React.createFactory, even if importFactory is set to false.

Not sure if this is intentional (then the documentation should probably mention this) or I am doing something wrong.

**Comment by mistadikay** [comment]
Hi, could you provide an example of your configuration and components file structure?

**Comment by PTihomir** [comment]
Ok, in the process of rewriting the rebem-starter-kit project for the purpose to show the issue, I noticed, that I missed one place where the mentioned flag should be set. When set, then everything started to work as expected.

``` javascript
module: {
        preLoaders: [
            {
                test: /\.js$/,
                loader: 'rebem-layers',
                query: {
                    layers: [
                        require('rebem-core-components'),
                        require('rebem-theme-reset'),
                        require('../src/theme-bootstrap'),
                        {
                            path: path.resolve('src/components/'),
                            files: {
                                main: 'index.js',
                                styles: 'styles.less'
                            },
                            importFactory: false
                        }
                    ],
                    consumers: [
                        path.resolve('src/unrebem-component')
                    ],

                   importFactory: false // this line was missing

                }
            },
            ...

Maybe the documentation could be more clear on where the importFactory should be set.
```

**Comment by mistadikay** [comment]
@PTihomir hey, just update the documentation. Hope it's more clear now

**Comment by PTihomir** [comment]
@mistadikay Yep, I think it's much better now :) Thanks!
